version: "3.8"
services:
  postgres:
    container_name: cashflow-db
    image: "postgres:16"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "cashflow", "-U", "test"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - "cashflow_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - cashflow_local
    ports:
      - "5432:5432"

  cashflow-api:
    image: ghcr.io/denniseckler/cashflow-api:main
    # image: cashflow-api:dev
    container_name: cashflow-api
    depends_on:
      - "postgres"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8089:8080"
    networks:
      - cashflow_local

  cashflow-ui:
    image: ghcr.io/denniseckler/cashflow-ui:main
    # image: cashflow-ui:dev
    container_name: cashflow-ui
    depends_on:
      - "cashflow-api"
    ports:
      - "4200:80"
    networks:
      - cashflow_local

  cashflow-auth:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: cashflow-auth
    depends_on:
      - postgres
    networks:
      - cashflow_local
    ports:
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: ${POSTGRES_URL}
      KC_HTTP_PORT: 9000
    command:
      - start-dev

networks:
  cashflow_local:
    name: cashflow_local
    driver: bridge

volumes:
  cashflow_data:
    name: "cashflow_data"
