version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: backend
    container_name: backend
    working_dir: /app
    ports:
      - "8080:8080"
      # Volume is only for developing locally and auto reload
    volumes:
    - ./Backend:/app

volumes:
  postgres:
    name: "postgres_data"
