version: "3.8"
services:
  postgres:
    container_name: cashflow-db
    image: "postgres:16"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - "cashflow_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - cashflow_local
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cashflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  cashflow-api:
    image: denniseckler/cashflow-api
    build: ./cashflowAPI/
    container_name: cashflow-api
    depends_on:
      - "postgres"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - cashflow_local

  cashflow-ui:
    image: denniseckler/cashflow-ui
    build: ./cashflowUI/
    container_name: cashflow-ui
    depends_on:
      - "cashflow-api"
    ports:
      - "4200:80"
    networks:
      - cashflow_local

networks:
  cashflow_local:
    name: cashflow_local
    driver: bridge

volumes:
  cashflow_data:
    name: "cashflow_data"
