services:
    devdb:
        container_name: devdb
        image: postgres:16
        environment:
            - 'POSTGRES_USER=dev'
            - 'POSTGRES_PASSWORD=dev'
            - 'POSTGRES_DB=devdb'
        ports:
            - '5432:5432'