CREATE TABLE IF NOT EXISTS category (
  id BIGINT NOT NULL PRIMARY KEY,
  label VARCHAR(100) NOT NULL UNIQUE,
  type VARCHAR(100) NOT NULL CONSTRAINT category_type_check CHECK (type IN ('FIXED', 'VARIABLE', 'UNIQUE', 'INCOME')),
  user_id VARCHAR(100) NOT NULL
)


