CREATE TABLE IF NOT EXISTS transaction (
  id BIGINT NOT NULL PRIMARY KEY,
  date DATE NOT NULL,
  amount NUMERIC(9,2) NOT NULL,
  user_id VARCHAR(100) NOT NULL,
  purpose VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  identifier_id BIGINT REFERENCES identifier(id) ON DELETE SET NULL
)

