/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashflowValidationErrorResponseSubErrorInner } from './cashflowValidationErrorResponseSubErrorInner';


export interface CashflowValidationErrorResponse { 
    statusCode?: number;
    message?: string;
    datetime?: string;
    subError?: Array<CashflowValidationErrorResponseSubErrorInner>;
}

