/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';
import { IdentifierResponse } from './identifierResponse';


export interface CategoryUpdateRequest { 
    id: number;
    label: string;
    userID: string;
    type: TransactionType;
    identifier?: Array<IdentifierResponse>;
}
export namespace CategoryUpdateRequest {
}


