/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileDescription { 
    dateIdx?: number;
    amountIdx?: number;
    purposeIdx?: number;
    sourceIdx?: number;
    year?: string;
    month?: string;
}

