/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonthlySummaryTest { 
    year: number;
    month: number;
    categoryTotals: { [key: string]: number; };
    totalExpenses: number;
}

