/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OverviewSummaryResponse { 
    year?: string;
    month?: string;
    fixed?: number;
    variable?: number;
    income?: number;
    unique?: number;
    diff?: number;
}

