/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentifierResponse } from './identifierResponse';


export interface TransactionResponse { 
    id?: number;
    date?: string;
    amount?: number;
    userID?: string;
    purpose?: string;
    source?: string;
    identifier?: IdentifierResponse;
}

