/**
 * Cashflow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TransactionType = {
    FIXED: 'FIXED',
    VARIABLE: 'VARIABLE',
    UNIQUE: 'UNIQUE',
    INCOME: 'INCOME',
    IGNORE: 'IGNORE'
} as const;
export type TransactionType = typeof TransactionType[keyof typeof TransactionType];

