INSERT INTO category (label, type, user_id)
VALUES ('Income', 'INCOME', 'gojo'),
       ('Miete', 'FIXED', 'gojo'),
       ('Fun', 'VARIABLE', 'gojo'),
       ('Insurance', 'FIXED', 'gojo'),
       ('Handy', 'FIXED', 'gojo'),
       ('Internet', 'FIXED', 'gojo'),
       ('Strom', 'FIXED', 'gojo'),
       ('Groceries', 'VARIABLE', 'gojo'),
       ('Transport', 'VARIABLE', 'gojo'),
       ('Abonnements', 'FIXED', 'gojo'),
       ('Ignore', 'IGNORE', 'gojo');

INSERT INTO identifier (label, category_id)
VALUES ('Musterfirma GmbH', (SELECT id FROM category WHERE label = 'Income')),
       ('Freelance Kunde AG', (SELECT id FROM category WHERE label = 'Income')),
       ('Wohnung', (SELECT id FROM category WHERE label = 'Miete')),
       ('BACKEREI MUELLER', (SELECT id FROM category WHERE label = 'Fun')),
       ('AMAZON EU SARL', (SELECT id FROM category WHERE label = 'Fun')),
       ('CAFE CENTRAL', (SELECT id FROM category WHERE label = 'Fun')),
       ('STARBUCKS GMBH', (SELECT id FROM category WHERE label = 'Fun')),
       ('Provinzial', (SELECT id FROM category WHERE label = 'Insurance')),
       ('Mobilphone', (SELECT id FROM category WHERE label = 'Handy')),
       ('TELEKOM DEUTSCHLAND', (SELECT id FROM category WHERE label = 'Internet')),
       ('STADTWERKE EVER', (SELECT id FROM category WHERE label = 'Strom')),
       ('ALDI SUED SAGT DANKE', (SELECT id FROM category WHERE label = 'Groceries')),
       ('DM DROGERIE MARKT', (SELECT id FROM category WHERE label = 'Groceries')),
       ('EDEKA ZENTRALE AG', (SELECT id FROM category WHERE label = 'Groceries')),
       ('LIDL DIENSTLEISTUNG', (SELECT id FROM category WHERE label = 'Groceries')),
       ('ARAL AG', (SELECT id FROM category WHERE label = 'Transport')),
       ('BAHN.DE', (SELECT id FROM category WHERE label = 'Transport')),
       ('DEUTSCHE POST AG', (SELECT id FROM category WHERE label = 'Transport')),
       ('PAYPAL EUROPE', (SELECT id FROM category WHERE label = 'Transport')),
       ('NETFLIX INTERNATIONAL', (SELECT id FROM category WHERE label = 'Abonnements')),
       ('SPOTIFY AB', (SELECT id FROM category WHERE label = 'Abonnements')),
       ('NotRelevant', (SELECT id FROM category WHERE label = 'Ignore'));