spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
