#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/test
#    url: jdbc:postgresql://localhost:5432/test
#    username: test
#    password: test
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/myData
  datasource:
    url: jdbc:h2:mem:customdb
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2