openapi: 3.1.0
info:
    version: 1.0.1
    title: Cashflow App
    summary: Cashflow Manager
    description: REST API Server for Transaktions
paths:
    /categories:
        get:
            description: Returns all Categories for a specific user
            responses:
                '200':
                    description: A list of pets.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/category'
components:
    schemas:
        category:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                label:
                    type: string
        identifier:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                label:
                    type: string