export enum Category {
  DENNIS = 'Dennis',
  SVETI = 'Sveti',
  GUTSCHRIFT = 'Gutschrift',
  MIETE = 'Miete',
  STROM = 'Strom',
  INTERNET = 'Internet',
  HANDY = 'Handy',
  VERSICHERUNG = 'Versicherung',
  GEZ = 'GEZ',
  ABONNEMENT = 'Abonnement',
  LEBENSMITTEL = 'Lebensmittel',
  HAUSHALTSMITTEL = 'Haushaltsmittel',
  KLEIDUNG = 'Kleidung',
  MOBILITAET = 'Mobilitaet',
  GESCHENKE = 'Geschenke',
  AUSGEHEN = 'Ausgehen',
  SONSTIGES = 'Sonstiges',
  LEER = 'Leer',
}
