spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql
  management:
    endpoints:
      web:
        cors:
          allowed-origins: "/*"